services:
  - type: web
    name: nutriai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -b 0.0.0.0:$PORT --access-logfile - --error-logfile - --log-level info --timeout 120
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PYTHONUNBUFFERED
        value: "1"
